"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/Header"
import Footer from "@/components/layout/Footer/Footer";
import Login from "@/components/Login/Login";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";



const inter = Inter({ subsets: ["latin"] });
import { usePathname } from "next/navigation";
import MainLayout from "@/components/layout/Header/Header";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathName = usePathname();
  const decider = pathName == "/login";

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        {decider ? (
          <Login />
        ) : (
          <MainLayout>
            {children}
          </MainLayout>
        )}
      </body>
    </html>
  );
}
